Organisms todo card
JunPlayGround/Jun-frontend-basic-2023-todoapp pull request #6
Opened 2023-08-11 19:24 UTC by JunPlayGround

タスクを編集してもその名前が表示されません
原因はMoleculesにあるかもしれません
アドバイスをお願いします。

2023-08-12 06:48 UTC, Kotaro0722 commented on src/components/Organisms/index.jsx
> +            taskList.map(function (task,index){
書き方を統一するためにここは
`taskList.map((task,index)=>{})`
のようにしておきましょう！

2023-08-12 06:48 UTC, Kotaro0722 commented on src/components/Organisms/index.jsx
> +              return  <Tasks onTaskChange={onTaskNameChange} onTaskComplete={onTaskComplete} taskName={task.name} defaultIsEditing={task.initializing} />;
Taskに与えるpropsに修正すべき点があるかと思います。
taskName,defaultIsEditingに関してはよいと思いますが、ほかのkey,onTaskComplete,onTaskNameChangeに関しては修正していただきたいと思います。
・key:追加してください。(使用しないかもしれませんが)
・onTaskChange:関数名を直接記述するのではなく、関数として与えその処理部分に記述する方法でやってみてください。引数にも注意してやってください。
・onTaskComplete:onTaskChangeと同様にやってみてください。

2023-08-12 06:48 UTC, Kotaro0722 commented on src/components/Organisms/index.jsx
> +  const [taskList, setTaskList] = useState([]);
useStateの使い方としては合っていますが、初期値を修正していただきたいです。
後に自分で見てもわかりやすいように初期値にnameとinitializingを連想配列として入れておいてください。

2023-08-14 11:17 UTC, higashiji2000 requested changes

2023-08-14 11:17 UTC, higashiji2000 commented on src/components/Organisms/index.jsx
> +    setTaskList(addList.concat({ name: "", initializing: true }));
```suggestion
    setTaskList([...taskList, { name: "", initializing: true }]);
```
別のオブジェクトとして管理するのはGoodです！
このようにすると1行でかけたりします。

2023-08-14 11:17 UTC, higashiji2000 commented on src/components/Organisms/index.jsx
> +    setTaskList(addList.concat({ name: "", initializing: true }));
deleteList, changeList も同様

2023-08-14 11:17 UTC, higashiji2000 commented on src/components/Organisms/index.jsx
> +`;
背景色や幅などが[お手本のstorybook](http://shinonome.io/frontend-basic-todoapp-storybook/?path=/story/organisms-todocard--default)と異なるので、スタイルの確認をお願いします
（お手本のstoryは中身が永続化されていますが、後で実装するので現時点でその必要はありません）

2023-08-16 07:56 UTC, higashiji2000 requested changes

2023-08-16 07:56 UTC, Higashiji commented on src/components/Organisms/index.jsx
> +                onTaskComplete(index);
```suggestion
                onTaskComplete({index});
```
こんな感じに修正するとよいかと！

解説：
16行目の関数定義の部分で、 `{index: 何らかの値 }` を受け取るようになっていますが、現状 `index` (number) を第一引数にそのまま渡してしまっているため、 `onTaskComplete` 実行時には  `index` が `undefined` になってしまっています。

これにより、「どこをクリックしても一番上の要素が消える」という状況が再現しているものと思われます。

![image](https://github.com/JunPlayGround/Jun-frontend-basic-2023-todoapp/assets/83479175/2b4f1c67-d471-405c-99b2-32d7cb72b411)

2023-08-16 07:56 UTC, higashiji2000 commented on src/components/Organisms/index.jsx
> +      changeList.splice(index, 1,{ name: value, initializing: true })
```suggestion
      changeList.splice(index, 1,{ name: value, initializing: false })
```
`initializing` は、「最初から編集モードになっているかどうか」を管理したいので、一度編集したものは `false` にしたいです。

2023-08-16 08:03 UTC, higashiji2000 commented on src/components/Organisms/index.jsx
> +  };
Reactはよく関数型プログラミングの文脈でも語られます。
特に、副作用をなるべく起こさないという意識を持っておくことは大切です。

配列の `filter` メソッド (`Array.prototype.filter`) などを使うと、より関数型っぽく、宣言的に、副作用を起こさない形で実装することができます。

今回はこの実装でも全く問題ありませんが、大規模プロジェクトなどではぜひ意識してみてください。

参考：https://qiita.com/terry_6518/items/4b39826d9ee76076a0a7

2023-08-16 09:45 UTC, higashiji2000 requested changes

2023-08-16 09:45 UTC, higashiji2000 commented on src/components/Organisms/index.jsx
> +                onTaskComplete(index);
```suggestion
              onTaskComplete={() => {
                onTaskComplete({index});
```
こうでした🙏

`onTaskComplete` に渡す関数は、 `Tasks` コンポーネント内部で  `button` 要素の `onClick` 属性に渡されているため、第一引数にはイベントオブジェクトが入ってきてしまっていました。
41行目のindexを使うようにしましょう。

![image](https://github.com/JunPlayGround/Jun-frontend-basic-2023-todoapp/assets/83479175/27f7d43f-593f-49a0-9ec1-df67eca176ec)
（ログ出力結果）

2023-08-16 11:53 UTC, higashiji2000 approved these changes
LGTM☂️

2023-08-16 11:53 UTC, higashiji2000 commented on src/components/Organisms/index.jsx
> +      })
```suggestion
    const listIndex = index;
    setTaskList(
      taskList.filter((value, index, list) => {
        return index !== listIndex;
      })
```
deleteList と taskList は同じなので、これでもよさそうです

2023-08-16 13:06 UTC, merged